pushing up changes for the night

diff --git a/resource/out b/resource/out
--- a/resource/out
+++ b/resource/out
@@ -11,22 +11,35 @@ BBlue='\033[1;34m'   # Bold Blue
 BYellow='\033[1;33m' # Bold Yellow
 NC='\033[0m'         # No Color
 
-source=$1
-if [[ -z "$source" ]]; then
+
+base_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
+
+# source "$base_dir/resource/lib/logger.sh"
+# source "$base_dir/resource/lib/error-codes.sh"
+
+working_dir=${1:-}
+
+if [ -z "$working_dir" ]; then
   echo "usage: $0 <path/to/source>"
   exit 1
 fi
-# for jq
-PATH=/usr/local/bin:$PATH
-export TMPDIR=${TMPDIR:-/tmp/confluence_pr}
-mkdir -p "${TMPDIR}"
-payload=$(mktemp "$TMPDIR/resource-request.XXXXXX")
-cat >"$payload" <&0
 
+cd "$working_dir"
+
+TMPDIR=${TMPDIR:-/tmp}
+PAYLOAD=$(mktemp "$TMPDIR/bitbucket-branch-mgmt-resource-request.XXXXXX")
+
+cat > $PAYLOAD <&0
+
+get_config() {
+  local key=${1:?config key null or not set}
+  local default=${2:-}
+  jq -r --arg default "$default" "$key // \$default" < "$PAYLOAD"
+}
 
 # #from the resource
-bitbucket_url=$(jq -r '.source.bitbucket_url // ""' <"$payload")
-access_token=$(jq -r '.source.access_token // ""' <"$payload")
+bitbucket_url=$(jq -r '.source.bitbucket_url // ""' <"$PAYLOAD")
+access_token=$(jq -r '.source.access_token // ""' <"$PAYLOAD")
 
 
 # #from the task
@@ -36,12 +49,14 @@ get_option() {
   echo "$OPTIONS" | jq -r --arg default "$default" "$key // \$default"
 }
 
-# ^^ this is going to make things way cleaner.
-#so instead of:
-  # org=$(jq -r '.params.org // ""' <"$payload")                           #required
+params=$(get_config '.params')
+if [ -z "$params" ]; then
+  printf '%b[ERROR]%b %s\n' "$BRed" "$NC" "invalid PAYLOAD (missing params)"
+  exit 1
+fi
 
-#it will be like this:
-to_branch=$(get_option '.to_branch')
+
+
 
 ##do things
 # convert the single command into a single element array
@@ -58,7 +73,7 @@ echo "$params" | jq -c '.commands[]' | while read -r OPTIONS; do
     if [ -f "$command_script" ]; then
       source "$command_script"
     else
-      printf '%b[ERROR]%b %s\n' "$BRed" "$NC" "invalid payload (unknown command: $command)"
+      printf '%b[ERROR]%b %s\n' "$BRed" "$NC" "invalid PAYLOAD (unknown command: $command)"
       exit 1
     fi
   )
